# Generated by Django 5.1.6 on 2025-05-20 13:31

import django.db.models.deletion
import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_cours_objectif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ethnie',
        ),
        migrations.AddField(
            model_name='user',
            name='langues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.langues'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='pdf',
            field=models.FileField(upload_to=frontend.models.lecon_file_path, verbose_name='Ajouter la/les fichiers de documentation qui accompagne la vidéo'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='video',
            field=models.FileField(default='X', upload_to=frontend.models.lecon_file_path, verbose_name='Ajouter la version vidéo de la leçon'),
        ),
    ]
