# Generated by Django 5.1.6 on 2025-06-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_user_ethnie_user_langues_alter_lecon_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(verbose_name='Veuillez entrer votre question ici')),
                ('reponse1', models.CharField(verbose_name='Réponse 1')),
                ('reponse2', models.CharField(verbose_name='Réponse 2')),
                ('reponse3', models.CharField(verbose_name='Réponse 3')),
                ('reponse_correct', models.CharField(verbose_name='Bonne réponse ici !')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.semaine')),
            ],
        ),
    ]
