# Generated by Django 5.1.6 on 2025-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=520, verbose_name='Veuillez entrer votre question ici'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='reponse1',
            field=models.CharField(max_length=520, verbose_name='Réponse 1'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='reponse2',
            field=models.CharField(max_length=520, verbose_name='Réponse 2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='reponse3',
            field=models.CharField(max_length=520, verbose_name='Réponse 3'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='reponse_correct',
            field=models.CharField(max_length=520, verbose_name='Bonne réponse ici !'),
        ),
    ]
