# Generated by Django 5.1.6 on 2025-06-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_quiz_question_alter_quiz_reponse1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='cours',
            new_name='semaine',
        ),
    ]
