# Generated by Django 5.1.6 on 2025-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_rename_cours_quiz_semaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='reponse1',
            field=models.CharField(max_length=520, verbose_name='Réponse fausse 1'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='reponse2',
            field=models.CharField(max_length=520, verbose_name='Réponse fausse 2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='reponse3',
            field=models.CharField(max_length=520, verbose_name='Réponse fausse 3'),
        ),
    ]
