# Generated by Django 5.1.6 on 2025-06-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_quiz_reponse1_alter_quiz_reponse2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quizz', to='frontend.semaine'),
        ),
    ]
